site_name: Team Documentation
site_description: Documentationforourawesometeam
site_author: Timm Hinsch

theme:
  name: dracula

nav:
  - Home: index.md
  - About: about.md
  - Guidelines: guidelines.md