site_name: Team Documentation
site_description: Documentationforourawesometeam
site_author: Timm Hinsch

theme:
  name: dracula

nav:
  - Home: index.md
  - About: about.md
  - Getting Started: gettingStarted.md
  - Guidelines: guidelines.md
  - Technology Documentation: architectureAndTechnology.md
  - Changelog and Versioncontrol: versioncontrol.md
  - GitHub Actions: githubActions.md
  - Unit Tests: unitTest.md
  

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  
  
  
  
